### PR TITLE
Empty exclusion list

### PR DESCRIPTION
**Pull request by Bisaloo**
- [x] `Nike.com (partial)`: Fixed server side: nikeplus.com now redirects to nike.com
- [x] `PJ Media`: already disabled upstream
- [x] `Slashdot.org (partial)`: fixed server side. Test https://mobile.slashdot.org/
- [x] `Delta.com (partial)`: fixed in EFForg/https-everywhere#9877
- [x] `Cargo (partial)`: fixed server side
- [x] `TMZ.com`: Fixed server side. Further ruleset cleanup in EFForg/https-everywhere#14651
- [x] `BusinessInsider.com (partial)`: fixed server side. Test http://www.businessinsider.com/silicon-valley-100-2016-6
- [x] `Tesco (partial)`: Fixed server side. See EFForg/https-everywhere#4615
- [x] `Vodafone.ie (partial)`: fixed in EFForg/https-everywhere#14648
- [x] `iDownloadBlog (partial)`: fixed server side. Test http://idownloadblog.com/
- [x] `Cisco.com (partial)`: already disabled upstream
- [x] `GQ.com (partial)`: Fixed server side. Site now serves STS header.
- [x] `Where 2 Get It (partial)`: fixed in EFForg/https-everywhere#14649
- [x] `Thompson Hotels.com (partial)`: fixed in EFForg/https-everywhere#14650

### CODE REVIEW

**Comment by Bisaloo** [comment]
@diracdeltas, should the whitelist just be emptied or completely removed alongside related code?

**Comment by cschanaj** [comment]
@diracdeltas it might worth merging this and update the ruleset to `2018.4.2` when a new release is made in EFForg/https-everywhere/issues/14907

**Comment by diracdeltas** [comment]
Sorry for the delay - I will take a look at this next time we update our HTTPS Everywhere version

**Comment by diracdeltas** [comment]
needs rebase but otherwise lgtm. sorry for dropping the ball on this.

**Comment by Bisaloo** [comment]
@diracdeltas, I rebased my changes on top of master. It should be okay now.

**Review by diracdeltas — APPROVED** [review]

**Comment by diracdeltas** [comment]
thanks!

**Pull request merged**
