### PR TITLE
Upgrade level DB dependency and increase zip/gzip compression level

### LINKED ISSUE #37: Level DB dependency is out of date
We're on 5.0.1, 6.0.1 is out.

### PR DESCRIPTION
**Pull request by fmarier**
Fixes #37. Cuts down download size by 3%.

No code changes needed to accommodate the new version of LevelDB.

### CODE REVIEW

**Comment by fmarier** [comment]
Tested manually using the instructions at https://github.com/brave/https-everywhere-builder#testing-locally

**Review by bsclifton — APPROVED** [review]
🎉 ++

We should be able to run the job for real to verify this works - if there's a problem (environment), then we can revert. But you're on Linux (which is what Jenkins will run this on), so I think we're G2G

**Comment by fmarier** [comment]
Failed build is because of `minimist`, which I'll be fixing in #35.

**Comment by fmarier** [comment]
My [build](https://ci.brave.com/job/brave-core-ext-https-everywhere-update-publish/20/) succeeded and after upgrading the component manually to 1.0.15 from `brave://components/` I tested it successfully with https://https-everywhere.badssl.com/.

**Pull request merged**
