### PR TITLE
Fix npm run build failure on Windows platform

### LINKED ISSUE #5: npm run build fails on Windows
`npm run build` fails on a vanilla Windows 10 installation with the following error:

```
https-everywhere-builder\scripts\preloadHTTPSE.js:154
              throw err
              ^

Error: Command failed: zip -r httpse.leveldb.zip httpse.leveldb && tar -czf httpse.leveldb.tgz httpse.leveldb
'zip' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

It's probably due to a lack of zip/unzip utilities in a standard Windows install. Probably better to use an npm zip module if possible, for portability.

### PR DESCRIPTION
**Pull request by cschanaj**

### CODE REVIEW

**Comment by cschanaj** [comment]
@diracdeltas this PR makes `https-everywhere-builder` portable to Windows. Would you be interested to take a look?

**Comment by diracdeltas** [comment]
looks good but we should make sure the output files work on all platforms. unfortunately i don't think we can test this by just checking the hash of the output files before and after this change because zip is non-deterministic :(.

i probably won't get to it this week but will add it to my todo. cc'ing @emerick in case he has cycles

**Comment by cschanaj** [comment]
@diracdeltas sorry for force-pushing, there was an merge conflict on the `package.json` file. please let me know if this is still needed. thanks.

**Comment by diracdeltas** [comment]
assigning to @emerick for review

**Pull request closed without merging**
