### PR TITLE
Implement ruleset signature validation

### PR DESCRIPTION
**Pull request by pipboy96**
I tried to avoid changes outside download-related code to make this PR easier to review. I plan to make more PRs to improve code quality later.

### CODE REVIEW

**Comment by pipboy96** [comment]
This is ready for review, sorry for force-pushing. You are free to change this code as you see fit before merging. There is a side effect of this change that the new code no longer creates a temporary file called `./https-everywhere/rules/default.rulesets`. If you need the code to create this file, please tell me.

**Comment by fmarier** [comment]
@pipboy96 Thanks for the PR! I'm sorry I haven't had time to test and review it yet. I was on holiday when you submitted it. I'll try to make time for this next week.

**Comment by pipboy96** [comment]
@fmarier Don't worry much, there is no need to rush, especially if it makes missing possible mistakes more likely.

**Comment by pipboy96** [comment]
@fmarier Is there something else I can work on? I would personally like the generated LevelDB files to also be signed and verified by the browser. Can I try to implement this?

**Comment by pipboy96** [comment]
@fmarier Any update?

**Review by fmarier — APPROVED** [review]
Code looks great. Thanks so much for this @pipboy96! I'm sorry I took so long to merge this.

I verified that this new branch generates the exact same JSON file as master.

`npm audit` is clean.

**Comment by pipboy96** [comment]
@fmarier No problem. Thanks for merging.

**Comment by fmarier** [comment]
> Is there something else I can work on? I would personally like the generated LevelDB files to also be signed and verified by the browser. Can I try to implement this?

I recently talked with EFF people and they're working on something that's very interesting: a [rust library](https://github.com/EFForg/https-everywhere-lib-core) to parse and apply the rulesets. So at this point, I think that if we change how things are done in Brave, it's likely to be to move to that library (and pull the JSON rulesets directly) so that we can rip out our C++ ruleset parser (https://github.com/brave/brave-browser/issues/5280).

If you did want to work on something else HTTPS Everywhere-related in Brave, I believe that we have a bug somewhere when it comes to the exceptions built into the rulesets (https://github.com/brave/brave-browser/issues/5124).

In any case, thanks again for adding signature checking. It's a great thing to have!

**Comment by pipboy96** [comment]
@fmarier I would like to help with that too. Any suggestions where to start?

**Comment by fmarier** [comment]
> Any suggestions where to start?

Let's follow up in the other bug directly: https://github.com/brave/brave-browser/issues/5124#issuecomment-521469679

**Pull request merged**
